README.md
index.d.ts
index.js
index.test-d.ts
package.json
tests/plugin.test.js
tests/util.test.js

Expose the process metrics sampler. I think it can be useful to perform custom logics using the process status.

Feat expose doc

---

.github/workflows/bench.yml
.github/workflows/merge.yml
.github/workflows/release.yml

ci: add bench workflow

---

README.md
index.d.ts
index.js
tests/plugin.test.js

feat: allow custom Dats client

---

index.test-d.ts
tests/plugin.test.js

test(types): added type tests custom dats client

---

index.js
tests/helpers/statsdTCP.js
tests/plugin.test.js

fix(TCP): fixed tcp

---

.github/workflows/bench.yml
.github/workflows/merge.yml
.github/workflows/release.yml
package-lock.json

ci: removes npm cache custom action

---

index.d.ts
index.test-d.ts
package-lock.json

chore(types): added missing type for FastifyContextConfig

---

index.d.ts
index.test-d.ts
package-lock.json
package.json

Update dats to version 2.
BREAKING CHANGE: there might be breaking changes in the new dats version.

chore(deps): update dats to version 2

---

benchmarks/fixtures/withDynamicModeMetrics.js
benchmarks/fixtures/withStaticModeMetrics.js
package.json

test: add dynamic mode benchmark

---

README.md

Minor fixes :wink: about missing stats and a few inconsistencies.
-   [x] Documentation Update (if none of the other choices apply)

Docs_minor_fixes

---

README.md
examples/nesting.js
index.d.ts
index.js
index.test-d.ts
tests/configuration.test.js
tests/helpers/utils.js
tests/metrics-collection.test.js

Add the possibility to pass `true` or `false` to toggle all the routes metrics.
-   [x] New feature (non-breaking change which adds functionality)

Routes_opts_improvement

---

index.d.ts
index.test-d.ts

Fix type issues with `FastifyContextConfig`.
close #149

fix: fixed types

---

index.d.ts
index.test-d.ts

This will integrate the type hotfix in #151  and various dependabot pr

Publish Next

---

index.js
tests/dynamic-mode.test.js

Fix the setup of the 404 test in dynamic mode that wasn't hitting the `onRequestHook`.

test: fix 404 setup

---

.github/workflows/bench.yml
.github/workflows/merge.yml
.github/workflows/release.yml
.github/workflows/test.yml
README.md
index.js
lib/hooks.js
package-lock.json
tests/helpers/utils.js

closes #229
BREAKING CHANGES: fastify major update

feat(fastify): updated to v4

---

MIGRATION_GUIDE.md
README.md
examples/dynamic_mode.js
index.test-d.ts
lib/decorate.js
lib/routes/dynamic.js
lib/routes/static.js
lib/routes/util.js
tests/dynamic-mode.test.js
tests/helpers/utils.js
tests/metric.test.js

In this MR we are fixing the Fastify deprecation that says we cannot access context from the request anymore in version 5
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Closes #316 
/cc @mdoria12

fix: fix fastify deprecation

---

.github/workflows/backmerge.yml
.releaserc.json
package-lock.json
package.json

In this MR we add an action to perform the back merge into the `next` branch since the …

ci(actions): add backmerge action

---

package-lock.json
package.json

feat: dats@5 node@18 npm@9

---

.github/workflows/test.yml

Windows builds are constantly failing to install. Let's remove them.

ci: remove windows

---

package.json

Since version 3 we have an incompatibility woth eslint that is solved
only in the alpha version fo the plugin.
See https://github.com/prettier/eslint-plugin-prettier/issues/562
-   [ ] …

chore(deps): fix prettier upgrade

---

package.json

Backmerge main

---

examples/default_tcp.js
examples/default_udp.js
examples/dynamic_mode.js
examples/nesting.js
examples/only_routes.js
index.test-d.ts
lib/routes/dynamic.js
lib/routes/static.js
lib/routes/util.js
package.json
tests/configuration.test.js
tests/dynamic-mode.test.js
tests/helpers/utils.js
tests/static-mode.test.js

fix: fastify depracation notice

---

.github/workflows/release.yml
.github/workflows/test.yml
package.json

Minor fixes
